### ISSUE TITLE
Open the linked zoom meeting in a new window or tab

### ISSUE THREAD

**Issue by SruliE** [AnalyzePlatypus/next-meeting-static-site#1]
**Problem**: 
After joining (& checking out a meeting), you need to hit the back button to be able to see the other meetings available.

**Solution**: 
Open all zoom links in a new tab.    
     _See_: ["HTML \<a\> target Attribute"](w3schools.com/tags/att_a_target.asp)
     `<a title="Join meeting" target="_blank" x-show="!session.connectionDetails.mustContactForConnectionInfo &amp;&amp; session.connectionDetails.joinUrl" x-bind:href="session.connectionDetails.joinUrl" class="button-primary fixed-width mr-2 sm:mr-4" href="https://zoom.us/j/0000000000?pwd=VTU...z09">
      Join&nbsp;›
    </a>`

**Comment by AnalyzePlatypus** [comment]
OK, fixed in [ef1adb8](https://github.com/AnalyzePlatypus/next-meeting-static-site/commit/ef1adb8060e16cf155c8e002e5a863bec2a3359d) and deployed.

Thx for the feedback!
